### ISSUE TITLE
能否生成python中文文档

### ISSUE THREAD

**Issue by skefy** [NauxLiu/Dash-docsets-CN#7]
python官方中文文档地址：https://docs.python.org/zh-cn/3/

**Comment by nauxliu** [comment]
已添加 https://github.com/nauxliu/Dash-docsets-CN/releases/tag/20190907

**Comment by westfly** [comment]
压缩包里是不是缺少文件，虽然不影响使用。
![image](https://user-images.githubusercontent.com/1453169/70194878-f1c74100-173e-11ea-9d04-1a8a65d5a76c.png)
